# Site settings
title: Jamie Lowry
email: jamie@jamielowry.com
description: > # this means to ignore newlines until "baseurl:"
  IT Professional based in San Francisco. Specializing in Enterprise Mac Management, 
  cloud services, and rapidly scaling internal infrastructure. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmelowry.github.io" # the base hostname & protocol for your site
twitter_username: jamielowry
github_username:  jmelowry

# Build settings
markdown: kramdown
